---
name: Catalyst-View-MicroMason
version: 0.04_01
author:
  - 'Jonas Alves C<jgda@cpan.org>'
abstract: MicroMason View Class
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.7
  Text::MicroMason: 1.99
provides:
  Catalyst::Helper::View::MicroMason:
    file: lib/Catalyst/Helper/View/MicroMason.pm
    version: 0.04_01
  Catalyst::View::MicroMason:
    file: lib/Catalyst/View/MicroMason.pm
    version: 0.04_01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
