--- 
abstract: MicroMason View Class
author: Jonas Alves C<< <jgda@cpan.org> >>
build_requires: 
  Catalyst::Runtime: 5.7
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-View-MicroMason
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::View::Templated: 0
  Text::MicroMason: 0
version: 0.05
